TECH_SKILLS=[
    "Python",
    "Java",
    "JavaScript",
    "React",
    "Node.js",
    "Express",
    "MongoDB",
    "MySQL",
    "HTML",
    "CSS",
    "Bootstrap",
    "Tailwind CSS",
    "Git",
    "GitHub",
    "Docker",
    "AWS",
    "Flask",
    "Django",
    "FastAPI",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Pandas",
    "NumPy",
    "REST API",
    "Spring Boot",
    "C",
    "C++",
    "PHP"
]